### ISSUE TITLE
Kucoin Testnet Faucet?

### ISSUE THREAD

**Issue by BarneyChambers** [kucoin-community-chain/any-advice-issue#16]
I would like to start getting involved on testing your new community chain and also adding my DEX onto this chain as well (I work for the Umbria Network team)

Is there a testnet faucet for KCS token? I would also like to know what some of the links to community pages you might have are (discord, telegram, etc) so that I can chat with likeminded devs using the KCS testnet

I know this post isn't a conventional issue message, but I was struggling to find the appropriate place for this message. 

Thanks!

**Comment by lingyun92** [comment]
https://faucet-testnet.kucoin.one/

**Comment by Bonjur** [comment]
> https://faucet-testnet.kucoin.one/

It is broken
