### ISSUE TITLE
Kucoin transaction 

### ISSUE THREAD

**Issue by JBMONEY** [kucoin-community-chain/any-advice-issue#20]
I had some USDC coin on Kucoin Exchange and I was trying to send it to coinbase exchange and did not know that Coinbase does not support KCC The transaction went through but was not received in my coinbase wallet I want to know what I can do to get these funds back I went on the KCC discord because they don't have an email or a phone number for technical support and I didn't get any answer only that the funds were lost. Please help me to get these funds back I have a Transaction ID number 0x02e65b9f80bdc96f21f41fdd0fa048e2b4489d8adc7a8dce21c4b44cd7cd5825  Also my email address is Jasonbradley4040@yahoo.com

**Comment by caizhiyuanrise** [comment]
Hi
I would say the KCS you send KCS are 100% gone.. you sort of burned them unfortunate ;-/
As you say, Coinbase does not have Kucoin, so even if they would ever have, you will not find your KCS there, as you did not send it to a KCS address at all.
If you would have sent for example to a KCC or other network that supports KCS, then they would appear on that wallet as soon as the wallet supports KCS.
So, to what network did you send it to?
Good luck and stay calm ^_^

**Comment by caizhiyuanrise** [comment]
OH! now I read you send USDC... well, that is a bit different. But asking KuCoin will not help, as you send it to Coinbase.. you will have to ask the receiver if they support this Token in the near future on that network you send it to. Hard question... I would say I do not know if that will work at all. Am not in knowledge of Stablecoin networks...

**Comment by viaweb3** [comment]
yes， @caizhiyuanrise  is right
